# name : trial
# on:
#   push:
#     branches : [main]
#   workflow_dispatch:

# jobs:
#   say_hello:
#     runs-on: ubuntu-latest
#     steps:
#       - name: checkout the code
#         uses: actions/checkout@v3
#       - name: print greeting
#         run: echo "hello rania"


name: trial
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v3
      - name: print greeting
        run: echo "Hello Rania!"
